version: '3.3'

services:

  localstack:
    image: localstack/localstack:0.11.3
    container_name: cadmus-terraform
    ports:
      - "4566:4566"
      - "4569:4569"
      - "4570:4570"
      - "4574:4574"
      - "4572:4572"
      - "4586:4586"
      - "4568:4568"
      - "4582:4582"
      - "4587:4587"
      - "${PORT_WEB_UI-8181}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=dynamodb,dynamodbstreams,lambda,s3,logs,kinesis,kinesisanalytics,cloudwatchevents,cloudwatchlogs,cloudwatch,EventBridge
      - DEBUG=${DEBUG- }
      - DATA_DIR=/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=cadmus-lambda_localstack
    volumes:
      - "~/localstack/conf:/tmp"
      - "~/localstack/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack

  dynamo-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4569
    ports:
      - 8001:8001
    networks:
      - localstack

networks:
  localstack:
    driver: bridge