version: '3.3'

services:
  mongo-container:
    image: mongo:3.4.2
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
    networks:
      - mongodb-network

networks:
  mongodb-network:

