version: '3.3'

services:

  kafka:
    image: landoop/fast-data-dev
    environment:
      - ADV_HOST=127.0.0.1
      - BROWSECONFIGS=1
    volumes:
      - ~/localstack/landoop/data/:/data/
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
